-- =====================================================================
-- 0135_trabaje_con_nosotros.sql — punto B-18 de la auditoría
--
-- «En la parte final de la página colocar un Botón: Trabaje con nosotros que lo
--  lleve a una ventana para que coloque sus datos personales básicos: apellido
--  paterno, apellido materno, nombres, documento de identidad, correo
--  electrónico, grado de instrucción (secundaria, técnico, bachiller, maestría,
--  doctorado) y una descripción del puesto al que postula, sus habilidades, su
--  experiencia. Que se grabe en un registro con la fecha y hora que se registró
--  y que llegue un correo a los usuarios Admin y SuperAdmin.»
--
-- POR QUÉ `careers` Y NO `job_applications`
--
-- Ya existe `applications`: las postulaciones a los avisos de empleo que
-- publican los anunciantes. Son otra cosa —van dirigidas a un cliente, no a
-- nosotros— y confundirlas en un reporte sería un problema serio: acabaríamos
-- enseñando a un anunciante los currículums que la gente nos manda a nosotros.
-- Un nombre parecido invita justo a esa confusión, así que se llama distinto.
--
-- CÓMO ENTRA UNA POSTULACIÓN
--
-- Directo contra la tabla, con policy de INSERT para anon. Es distinto del
-- Libro de Reclamaciones (0034), que entra por una Edge Function porque tiene
-- que devolver un PDF firmado por el servidor. Aquí no hay nada que devolver, y
-- una función intermedia sería una pieza más que desplegar y mantener para
-- nada.
--
-- Lo que sí hace falta al abrir un formulario público es un freno: sin él,
-- cualquiera con la anon key —que va escrita en el bundle— puede llenar la
-- tabla. El trigger de abajo limita por correo y por documento, con el mismo
-- criterio de la 0124: se cuenta sobre las propias filas, sin tabla de
-- contadores que pueda desincronizarse.
--
-- Idempotente.
-- =====================================================================

create table if not exists public.careers (
  id                uuid primary key default gen_random_uuid(),
  -- Correlativo legible, para poder referirse a una postulación por teléfono
  -- sin dictar un uuid.
  code              bigint generated by default as identity,
  apellido_paterno  text not null,
  apellido_materno  text not null,
  nombres           text not null,
  doc_type          text not null default 'DNI',
  doc_number        text not null,
  email             text not null,
  phone             text,
  grado             text not null,
  puesto            text not null,
  -- Habilidades y experiencia, en un solo campo: pedir tres cajas separadas a
  -- alguien que postula desde el móvil es la mejor forma de que no postule.
  descripcion       text not null,
  status            text not null default 'nueva',
  -- Nota interna de quien la revisa. No la ve quien postula.
  nota              text,
  reviewed_by       uuid references public.profiles (id) on delete set null,
  reviewed_at       timestamptz,
  -- La fecha y hora del registro que pidió el cliente. La pone el servidor, no
  -- el reloj del teléfono, que puede estar en cualquier hora.
  created_at        timestamptz not null default now()
);

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'careers_status_check') then
    alter table public.careers add constraint careers_status_check
      check (status in ('nueva', 'revisada', 'descartada', 'contratada'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'careers_grado_check') then
    alter table public.careers add constraint careers_grado_check
      check (grado in ('secundaria', 'tecnico', 'bachiller', 'maestria', 'doctorado'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'careers_doc_type_check') then
    alter table public.careers add constraint careers_doc_type_check
      check (doc_type in ('DNI', 'CE', 'Pasaporte'));
  end if;
end $$;

create index if not exists careers_created_idx on public.careers (created_at desc);
create index if not exists careers_status_idx  on public.careers (status);
create index if not exists careers_email_idx   on public.careers (lower(email));
create index if not exists careers_doc_idx     on public.careers (doc_number);

-- ---------------------------------------------------------------------
-- El freno contra el llenado de la tabla
-- ---------------------------------------------------------------------
-- Tres por correo y tres por documento al día. Nadie postula cuatro veces en un
-- día por error, y quien de verdad quiera corregir algo puede escribir. Es
-- deliberadamente holgado: cortarle el paso a un candidato real sería peor que
-- tragarse tres filas de basura.
create or replace function public.frenar_postulaciones()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  c_tope constant int := 3;
  v_n int;
begin
  select count(*) into v_n
    from public.careers c
   where lower(c.email) = lower(new.email)
     and c.created_at > now() - interval '1 day';
  if v_n >= c_tope then
    raise exception 'Ya registramos tu postulación. Si necesitas corregir algo, escríbenos.'
      using errcode = 'check_violation';
  end if;

  select count(*) into v_n
    from public.careers c
   where c.doc_number = new.doc_number
     and c.created_at > now() - interval '1 day';
  if v_n >= c_tope then
    raise exception 'Ya registramos tu postulación. Si necesitas corregir algo, escríbenos.'
      using errcode = 'check_violation';
  end if;

  return new;
end;
$$;

revoke execute on function public.frenar_postulaciones() from public;

drop trigger if exists careers_frenar on public.careers;
create trigger careers_frenar
  before insert on public.careers
  for each row execute function public.frenar_postulaciones();

-- ---------------------------------------------------------------------
-- El aviso a Admin y Superadmin
-- ---------------------------------------------------------------------
-- Va en un trigger y no en el front por la misma razón que en la 0126: colgado
-- de la tabla, avisa entre por donde entre la postulación. Y como los tres
-- canales nacen activados desde la 0121, el correo que pidió el cliente sale
-- por la vía de siempre en vez de inventar un envío aparte.
create or replace function public.avisar_postulacion_nueva()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid    uuid;
  v_nombre text;
begin
  v_nombre := btrim(new.nombres || ' ' || new.apellido_paterno);

  for v_uid in
    select user_id from public.user_roles where role in ('admin', 'superadmin')
  loop
    perform public.notify_user(
      v_uid,
      'career_new',
      'Nueva postulación de trabajo',
      jsonb_build_object(
        'career_id', new.id,
        'code',      new.code,
        'nombre',    v_nombre,
        'puesto',    new.puesto,
        'grado',     new.grado
      )
    );
  end loop;

  return new;
exception
  when others then
    -- Un fallo avisando no puede tumbar el registro: la postulación de una
    -- persona vale más que nuestra campana.
    raise warning 'No se pudo avisar de la postulación %: %', new.id, sqlerrm;
    return new;
end;
$$;

revoke execute on function public.avisar_postulacion_nueva() from public;

drop trigger if exists careers_avisar on public.careers;
create trigger careers_avisar
  after insert on public.careers
  for each row execute function public.avisar_postulacion_nueva();

-- ---------------------------------------------------------------------
-- Quién ve qué
-- ---------------------------------------------------------------------
alter table public.careers enable row level security;

-- Cualquiera puede postular, con o sin cuenta: exigir registrarse para dejar un
-- currículum es perder a la mitad de los candidatos en la puerta.
drop policy if exists careers_public_insert on public.careers;
create policy careers_public_insert on public.careers
  for insert to anon, authenticated
  with check (true);

-- Leerlas es otra cosa: son datos personales de terceros (documento, correo,
-- teléfono), así que van por el módulo de permisos y no por `is_staff` a secas.
drop policy if exists careers_staff_select on public.careers;
create policy careers_staff_select on public.careers
  for select using (public.has_perm('Trabaje con nosotros', 'view'));

drop policy if exists careers_staff_update on public.careers;
create policy careers_staff_update on public.careers
  for update using (public.has_perm('Trabaje con nosotros', 'edit'));

-- Nadie borra desde la aplicación. Una postulación descartada se marca, no se
-- destruye: alguien puede querer saber por qué se descartó.

grant insert on public.careers to anon, authenticated;
grant select, update on public.careers to authenticated;
-- La secuencia de `code` la usa el INSERT de anon; sin esto el alta falla con
-- "permission denied for sequence".
do $$
declare v_seq text;
begin
  v_seq := pg_get_serial_sequence('public.careers', 'code');
  if v_seq is not null then
    execute format('grant usage, select on sequence %s to anon, authenticated', v_seq);
  end if;
end $$;

-- ---------------------------------------------------------------------
-- El módulo en la matriz de permisos
-- ---------------------------------------------------------------------
-- Admin y superadmin gestionan. Soporte mira, porque puede atender a alguien
-- que llama preguntando por su postulación. Moderador no entra: su trabajo son
-- los avisos y los chats, y aquí hay documentos de identidad de terceros.
-- `do nothing`, igual que en la 0129: si alguien ya los ajustó desde el panel
-- de Roles, un despliegue no se los pisa.
insert into public.role_permissions (role, module, can_view, can_edit, can_approve, can_delete)
values
  ('admin',      'Trabaje con nosotros', true,  true,  false, false),
  ('superadmin', 'Trabaje con nosotros', true,  true,  false, false),
  ('soporte',    'Trabaje con nosotros', true,  false, false, false),
  ('moderador',  'Trabaje con nosotros', false, false, false, false)
on conflict (role, module) do nothing;

comment on table public.careers is
  'B-18: postulaciones de "Trabaje con nosotros". NO confundir con `applications`, '
  'que son las postulaciones a los avisos de empleo de los anunciantes.';
